version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./CourseFind
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - HF_HOME=/cache/huggingface
    volumes:
      - ./CourseFind:/usr/src/app
      - sqlite_data:/usr/src/app/db #altered line
      - huggingface_cache:/cache/huggingface
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  huggingface_cache:
  sqlite_data:

  